version: "3.9"

services:
  my_salary_api:
    restart: always
    container_name: my_salary_api
    build:
      context: .
      dockerfile: docker/dockerfile
    environment:
      POSTGRES_PORT:
      POSTGRES_DB:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_HOST:
      POSTGRES_DB_SCHEMA:
      TRACEBACK:
    command: >
      sh -c "alembic upgrade head &&
             uvicorn main:app --host $APP_HOST --port $APP_PORT --workers $APP_UVICORN_WORKERS"
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    restart: always
    container_name: postgres_my_salary
    image: postgres:13-alpine3.15
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    environment:
      POSTGRES_PORT:
      POSTGRES_DB:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -V" ]
      interval: 5s
      timeout: 5s
      retries: 5
    command: -p ${POSTGRES_PORT}

volumes:
  postgres_volume:

