version: "3.9"

services:
  my_salary_api:
    restart: always
    environment:
      - COMPOSE_PROJECT_NAME
    container_name: my_salary_api
    build:
      context: .
      dockerfile: "docker/dockerfile"
    env_file:
      - .env
    command: >
      sh -c "alembic upgrade head &&
             uvicorn core.app:app --host $APP_HOST --port $APP_PORT --workers $APP_UVICORN_WORKERS"
    ports:
      - ${APP_PORT}:${APP_PORT}
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    restart: always
    container_name: postgres_my_salary
    image: postgres:13-alpine3.15
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -V" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    command: -p ${POSTGRES_PORT}

  redis:
    restart: always
    image: redis/redis-stack:latest

volumes:
  postgres_volume:

