FROM python:3.11-alpine
WORKDIR my_salary
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
# Настройка приложения
ENV LOGGING__LEVEL="INFO"
ENV APP_NAME="My_salary"
ENV APP_HOST="0.0.0.0"
ENV APP_PORT="8004"
ENV APP_UVICORN_WORKERS=1
ENV ALLOW_CREDENTIALS="True"
ENV SECRET_KEY=""
ENV KEY=""
ENV UVICORN_ARGS "main:app --host $APP_HOST --port $APP_PORT --workers $APP_UVICORN_WORKERS"

ENV POSTGRES__DB=""
ENV POSTGRES__USER=""
ENV POSTGRES__PASSWORD=""
ENV POSTGRES__HOST="host.docker.internal"
ENV POSTGRES__PORT=5432

RUN pip install --upgrade pip  --no-cache-dir
RUN pip install "poetry"
COPY poetry.lock pyproject.toml .
RUN poetry config virtualenvs.create false
RUN poetry install

COPY app .
CMD uvicorn $UVICORN_ARGS