name: Build
on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths-ignore:
      - ".github/workflows/*"
      - "docs/*"
      - ".env*"
      - ".gitignore"
      - "README.md"
      - "pyproject.toml"
      - "poetry.lock"
jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup
        run: echo "ok"

  push_to_docker_hub:
    runs-on: ubuntu-latest
    needs: [ build_test ]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: docker/dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/my_salary:latest
  deploy:
    runs-on: ubuntu-latest
    needs: [ push_to_docker_hub ]

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_SSH_HOST }}
          username: ${{ secrets.VPS_SSH_USERNAME }}
          key: ${{ secrets.VPS_SSH_SECRET }}
          port: ${{ secrets.VPS_SSH_PORT }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/my_salary:latest
            docker stop ${{ github.event.repository.name }}
            docker rm my_salary
            docker run --name my_salary -d -p ${{secrets.VPS_PORT}}:${{secrets.VPS_PORT}} -e POSTGRES__DB=${{secrets.POSTGRES__DB}} -e POSTGRES__USER=${{secrets.POSTGRES__USER}} -e POSTGRES__PASSWORD=${{secrets.POSTGRES__PASSWORD}} -e VK__TOKEN=${{secrets.VK__TOKEN}} -e VK__GROUP_ID=${{secrets.VK__GROUP_ID}} ${{ secrets.DOCKERHUB_USERNAME }}/my_salary:latest
            echo "✅Start container my_salary successfully"
